version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1
  aws-s3: circleci/aws-s3@4.0.0
  jvm: sailthru/jvm@0.3.0

executors:
  test_containers:
    docker:
      - image: cimg/openjdk:21.0
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD

references:
  workspace_root: &workspace_root
    ~/project

  persist_workspace: &persist_workspace
    persist_to_workspace:
      root: *workspace_root
      paths: .

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  container_config: &container_config
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.workers.max=2"
    docker:
      - image: cimg/openjdk:21.0

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - *persist_workspace
      - run:
          name: Install dependencies
          command: ./gradlew build -x test
      - run:
          name: Assemble ZIP
          command: ./gradlew buildZip
      - run:
          name: Dir structure after build
          command: ls build/distributions

  deploy_to_stage:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: Dir structure while deploying to stage
          command: ls
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: DEV_AWS_REGION
      - run:
          name: Check AWS version
          command: |
            aws --version
      - run:
          name: Check Identity
          command: |
            aws sts get-caller-identity
#      - aws-s3/copy:
#          from: build/distributions/mparticle-outgoing-lambda-1.0-SNAPSHOT.zip
#          to: s3://sailthru-lambda-packages-stage/mparticle-outgoing-lambda/${CIRCLE_SHA1}/package.zip
#      - run:
#          name: "Deploy mparticle outgoing package to Lambda to stage"
#          command: |
#            aws lambda update-function-code \
#              --function-name mparticle_outgoing_sqs_message_processor \
#              --s3-bucket sailthru-lambda-packages-stage \
#              --s3-key mparticle-outgoing-lambda/${CIRCLE_SHA1}/package.zip \
#              --publish

  deploy_to_prod:
    <<: *container_config
    steps:
      - *attach_workspace
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: PROD_AWS_REGION
      - run:
          name: Check AWS version
          command: aws --version
      - run:
          name: Check Identity
          command: |
            aws sts get-caller-identity
      - aws-s3/copy:
          arguments: |
            --acl private
          from: build/distributions/project.zip
          to: s3://sailthru-lambda-packages-prod/mparticle-outgoing-lambda/${CIRCLE_SHA1}/package.zip
      - run:
          name: "Deploy mparticle outgoing package to Lambda to production"
          command: |
            aws lambda update-function-code \
              --function-name mparticle_outgoing_sqs_message_processor \
              --s3-bucket sailthru-lambda-packages-prod \
              --s3-key mparticle-outgoing-lambda/${CIRCLE_SHA1}/package.zip \
              --publish

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - jvm/test:
          name: test
          context:
            - Docker Hub
            - Nexus Credentials
          executor:
            name: test_containers
          resource_class: medium
      - deploy_to_stage:
          context:
            - Docker Hub
            - Nexus Credentials
            - AWS ECR Push
          requires:
            - test
