version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1.1
  aws-s3: circleci/aws-s3@4.0.0
  jvm: sailthru/jvm@0.3.0

parameters:
  project_name:
    description: Name of the project
    type: string
    default: mparticle-outgoing-lambda

  java_version:
    description: String version of Java this project depends on.
    type: string
    default: "21.0"

executors:
  test_containers:
    parameters:
      java_version:
        type: string
    docker:
      - image: cimg/openjdk:<< parameters.java_version >>
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD

references:
  workspace_root: &workspace_root
    ~/project

  persist_workspace: &persist_workspace
    persist_to_workspace:
      root: *workspace_root
      paths: .

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  container_config: &container_config
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.workers.max=2"
    docker:
      - image: cimg/openjdk:21.0

workflows:
  build:
    jobs:
#      - jvm/test:
#          context:
#            - Docker Hub
#            - Nexus Credentials
#            - AWS OIDC
#            - "AWS Email Stage"
#          executor:
#            name: test_containers
#            java_version: << pipeline.parameters.java_version >>
#          matrix:
#            parameters:
#              resource_class:
#                - medium

      - jvm/publish_jar:
          name: publish_jar
          context:
            - Docker Hub
            - Nexus Credentials
            - AWS OIDC
            - "AWS Email Stage"
#          requires:
#            - jvm/test
          version: $CIRCLE_SHA1

#      - verify_zip:
#          <<: *container_config
#          steps:
#            - run:
#                name: Dir structure after build but before persisting
#                command: ls -R ~/project
