version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-s3: circleci/aws-s3@4.0
  jvm: sailthru/jvm@0.3.0

references:
  container_config: &container_config
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.workers.max=2"
    docker:
      - image: cimg/openjdk:17.0

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Install dependencies
          command: ./gradlew build -x test
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Assemble ZIP
          command: ./gradlew buildZip
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Run tests
          command: ./gradlew test

  deploy_to_stage:
    <<: *container_config
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_ACCESS_KEY_SECRET
          aws-region: DEV_AWS_REGION
      - run:
          name: Check AWS version
          command: |
            aws --version
      - aws-cli/run:
          command: aws sts get-caller-identity
      - aws-s3/copy:
          arguments: |
            --acl private
          from: build/distributions/project.zip
          to: s3://sailthru-lambda-packages-stage/mparticle-outgoing-lambda/${CIRCLE_SHA1}/package.zip
      - run:
          name: "Deploy mparticle outgoing package to Lambda to stage"
          command: |
            aws lambda update-function-code \
              --function-name mparticle_outgoing_sqs_message_processor \
              --s3-bucket sailthru-lambda-packages-stage \
              --s3-key mparticle-outgoing-lambda/${CIRCLE_SHA1}/package.zip \
              --publish

  deploy_to_prod:
    <<: *container_config
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID_PROD
          aws-secret-access-key: AWS_ACCESS_KEY_SECRET_PROD
          aws-region: PROD_AWS_REGION
      - run:
          name: Check AWS version
          command: aws --version
      - aws-cli/run:
          command: aws sts get-caller-identity
      - aws-s3/copy:
          arguments: |
            --acl private
          from: build/distributions/project.zip
          to: s3://sailthru-lambda-packages-prod/mparticle-outgoing-lambda/${CIRCLE_SHA1}/package.zip
      - run:
          name: "Deploy mparticle outgoing package to Lambda to production"
          command: |
            aws lambda update-function-code \
              --function-name mparticle_outgoing_sqs_message_processor \
              --s3-bucket sailthru-lambda-packages-prod \
              --s3-key mparticle-outgoing-lambda/${CIRCLE_SHA1}/package.zip \
              --publish

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy_to_stage:
          requires:
            - test
